Repository prgrms-web-devcourse-final-project/WEB2_3_NINETY-NINE_BE, pull requests merged in 2025-03, with the labels that each got.

#84 feat: event 북마크 기능 구현
  src/main/java/com/example/onculture/domain/event/controller/BookmarkController.java
  src/main/java/com/example/onculture/domain/event/domain/Bookmark.java
  src/main/java/com/example/onculture/domain/event/domain/ExhibitEntity.java
  src/main/java/com/example/onculture/domain/event/domain/FestivalPost.java
  src/main/java/com/example/onculture/domain/event/domain/Performance.java
  src/main/java/com/example/onculture/domain/event/domain/PopupStorePost.java
  src/main/java/com/example/onculture/domain/event/dto/BookmarkEventListDTO.java
  src/main/java/com/example/onculture/domain/event/dto/EventResponseDTO.java
  src/main/java/com/example/onculture/domain/event/repository/BookmarkRepository.java
  src/main/java/com/example/onculture/domain/event/service/BookmarkService.java
  src/main/java/com/example/onculture/global/exception/ErrorCode.java
Labels: Feat

#87 Feat/user/#86
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/domain/Gender.java
  src/main/java/com/example/onculture/domain/user/domain/Interest.java
  src/main/java/com/example/onculture/domain/user/domain/Profile.java
  src/main/java/com/example/onculture/domain/user/domain/Role.java
  src/main/java/com/example/onculture/domain/user/domain/Social.java
  src/main/java/com/example/onculture/domain/user/domain/User.java
  src/main/java/com/example/onculture/domain/user/dto/request/ModifyRequestDTO.java
  src/main/java/com/example/onculture/domain/user/dto/request/SignupRequestDTO.java
  src/main/java/com/example/onculture/domain/user/dto/request/TokenRequestDTO.java
  src/main/java/com/example/onculture/domain/user/dto/response/TokenResponse.java
  src/main/java/com/example/onculture/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/example/onculture/domain/user/dto/response/UserResponse.java
  src/main/java/com/example/onculture/domain/user/dto/response/UserSimpleResponse.java
  src/main/java/com/example/onculture/domain/user/model/Interest.java
  src/main/java/com/example/onculture/domain/user/model/LoginType.java
  src/main/java/com/example/onculture/domain/user/model/Role.java
  src/main/java/com/example/onculture/domain/user/model/Social.java
  src/main/java/com/example/onculture/global/response/SuccessResponse.java
Labels: Feat

#88 Feat/user/#77
  src/main/java/com/example/onculture/domain/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/domain/User.java
  src/main/java/com/example/onculture/domain/user/dto/request/ModifyRequestDTO.java
  src/main/java/com/example/onculture/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/example/onculture/domain/user/model/Interest.java
  src/main/java/com/example/onculture/domain/user/service/ImageFileService.java
  src/main/java/com/example/onculture/domain/user/service/TokenService.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/example/onculture/domain/user/service/UserServiceTest.java
Labels: Feat

#89 Feat/event/85
  src/main/java/com/example/onculture/domain/event/controller/BookmarkController.java
  src/main/java/com/example/onculture/domain/event/controller/PerformanceController.java
  src/main/java/com/example/onculture/domain/event/domain/Performance.java
  src/main/java/com/example/onculture/domain/event/dto/EventPageResponseDTO.java
  src/main/java/com/example/onculture/domain/event/dto/EventResponseDTO.java
  src/main/java/com/example/onculture/domain/event/dto/PerformanceDetailDTO.java
  src/main/java/com/example/onculture/domain/event/repository/PerformanceRepository.java
  src/main/java/com/example/onculture/domain/event/service/BookmarkService.java
  src/main/java/com/example/onculture/domain/event/service/PerformanceService.java
  src/test/java/com/example/onculture/domain/event/controller/BookmarkControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/PerformanceControllerTest.java
  src/test/java/com/example/onculture/domain/event/service/BookmarkServiceTest.java
  src/test/java/com/example/onculture/domain/event/service/PerformanceServiceTest.java
Labels: Feat

#91 feat: 유저가 북마크를 누른 공연 게시글 조회 재배치
  src/main/java/com/example/onculture/domain/event/controller/BookmarkController.java
  src/main/java/com/example/onculture/domain/event/service/BookmarkService.java
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/test/java/com/example/onculture/domain/event/controller/BookmarkControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/PerformanceControllerTest.java
  src/test/java/com/example/onculture/domain/event/service/BookmarkServiceTest.java
  src/test/java/com/example/onculture/domain/user/service/UserServiceTest.java
Labels: Feat

#92 feat: 소셜 게시판 상세 조회 응답 수정
  src/main/java/com/example/onculture/domain/socialPost/controller/SocialPostController.java
  src/main/java/com/example/onculture/domain/socialPost/dto/PostWithLikeResponseDTO.java
  src/main/java/com/example/onculture/domain/socialPost/repository/SocialPostLikeRepository.java
  src/main/java/com/example/onculture/domain/socialPost/service/SocialPostService.java
  src/test/java/com/example/onculture/domain/socialPost/controller/SocialPostControllerTest.java
  src/test/java/com/example/onculture/domain/socialPost/service/SocialPostServiceTest.java
Labels: Feat

#94 Feat/user/#93
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/dto/request/ModifyRequestDTO.java
  src/main/java/com/example/onculture/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/example/onculture/domain/oauth/handler/OAuth2SuccessHandlerTest.java
  src/test/java/com/example/onculture/domain/user/service/ImageFileServiceTest.java
  src/test/java/com/example/onculture/domain/user/service/TokenServiceTest.java
Labels: Feat

#104 feat: socialPost 목록 조회에 좋아요 여부 추가
  src/main/java/com/example/onculture/domain/socialPost/controller/SocialPostController.java
  src/main/java/com/example/onculture/domain/socialPost/dto/PostListResponseDTO.java
  src/main/java/com/example/onculture/domain/socialPost/dto/UserPostListResponseDTO.java
  src/main/java/com/example/onculture/domain/socialPost/repository/SocialPostLikeRepository.java
  src/main/java/com/example/onculture/domain/socialPost/service/SocialPostService.java
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/test/java/com/example/onculture/domain/socialPost/controller/SocialPostControllerTest.java
  src/test/java/com/example/onculture/domain/socialPost/service/SocialPostServiceTest.java
Labels: Feat

#113 feat: 공연 API 마무리 작업
  src/main/java/com/example/onculture/domain/event/controller/PerformanceController.java
  src/main/java/com/example/onculture/domain/event/dto/PerformanceDetailDTO.java
  src/main/java/com/example/onculture/domain/event/repository/PerformanceRepository.java
Labels: Feat

#115 Fix/profile/#111
  src/main/java/com/example/onculture/domain/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/service/TokenService.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/main/java/com/example/onculture/global/config/WebSecurityConfig.java
  src/main/java/com/example/onculture/global/utils/CookieUtil.java
  src/main/java/com/example/onculture/global/utils/jwt/JwtTokenProvider.java
Labels: Feat

#117 Fix/profile/#116
  src/main/java/com/example/onculture/domain/oauth/service/OAuth2UserCustomService.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/main/java/com/example/onculture/global/exception/ErrorCode.java
Labels: Fix

#123 Feat/user/#118
  src/main/java/com/example/onculture/domain/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/onculture/domain/user/domain/Profile.java
  src/main/java/com/example/onculture/domain/user/domain/User.java
  src/main/java/com/example/onculture/domain/user/service/EmailService.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/test/java/com/example/onculture/domain/oauth/handler/OAuth2SuccessHandlerTest.java
  src/test/java/com/example/onculture/domain/user/service/TokenServiceTest.java
  src/test/java/com/example/onculture/domain/user/service/UserServiceTest.java
Labels: Feat, Fix

#125 Feat/event/124
  src/main/java/com/example/onculture/OnCultureApplication.java
  src/main/java/com/example/onculture/domain/event/controller/CrawlController.java
  src/main/java/com/example/onculture/domain/event/controller/EventController.java
  src/main/java/com/example/onculture/domain/event/controller/ExhibitController.java
  src/main/java/com/example/onculture/domain/event/controller/FestivalController.java
  src/main/java/com/example/onculture/domain/event/controller/PopupStoreController.java
  src/main/java/com/example/onculture/domain/event/domain/ExhibitEntity.java
  src/main/java/com/example/onculture/domain/event/domain/Performance.java
  src/main/java/com/example/onculture/domain/event/dto/EventResponseDTO.java
  src/main/java/com/example/onculture/domain/event/dto/ExhibitDTO.java
  src/main/java/com/example/onculture/domain/event/dto/PerformanceDetailDTO.java
  src/main/java/com/example/onculture/domain/event/repository/ExhibitRepository.java
  src/main/java/com/example/onculture/domain/event/repository/FestivalPostRepository.java
  src/main/java/com/example/onculture/domain/event/repository/PerformanceRepository.java
  src/main/java/com/example/onculture/domain/event/repository/PopupStorePostRepository.java
  src/main/java/com/example/onculture/domain/event/service/ExhibitService.java
  src/main/java/com/example/onculture/domain/event/service/FestivalPostAddressUpdateService.java
  src/main/java/com/example/onculture/domain/event/service/FestivalService.java
  src/main/java/com/example/onculture/domain/event/service/PopupStoreService.java
  src/main/java/com/example/onculture/domain/event/task/EventScheduler.java
  src/main/java/com/example/onculture/domain/event/util/RegionMapper.java
  src/main/java/com/example/onculture/domain/socialPost/domain/Comment.java
  src/test/java/com/example/onculture/domain/event/controller/BookmarkControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/CrawlControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/EventControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/ExhibitControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/FestivalControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/PerformanceControllerTest.java
  src/test/java/com/example/onculture/domain/event/controller/PopupStoreControllerTest.java
  src/test/java/com/example/onculture/domain/event/service/ExhibitServiceTest.java
  src/test/java/com/example/onculture/domain/event/service/FestivalPostAddressUpdateServiceTest.java
  src/test/java/com/example/onculture/domain/event/service/FestivalServiceTest.java
  src/test/java/com/example/onculture/domain/event/service/PerformanceServiceTest.java
  src/test/java/com/example/onculture/domain/event/service/PopupStoreServiceTest.java
Labels: Feat

#135 Feat/user/#128
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/domain/User.java
  src/main/java/com/example/onculture/domain/user/dto/response/UserListResponse.java
  src/main/java/com/example/onculture/domain/user/repository/UserRepository.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
  src/main/java/com/example/onculture/global/exception/ErrorCode.java
  src/main/resources/static/index.html
  src/test/java/com/example/onculture/domain/user/service/UserServiceTest.java
Labels: Feat, Fix

#144 Feat : 소셜 로그인 완료 리다이렉트 URL의 파라미터인 액세스 토큰 앞에 Bearer 추가
  src/main/java/com/example/onculture/domain/oauth/handler/OAuth2SuccessHandler.java
Labels: Feat

#147 Feat/event/142
  src/main/java/com/example/onculture/domain/event/repository/PerformanceRepository.java
  src/main/java/com/example/onculture/domain/event/service/ExhibitService.java
  src/main/java/com/example/onculture/domain/event/service/FestivalService.java
  src/main/java/com/example/onculture/domain/event/service/PerformanceService.java
  src/main/java/com/example/onculture/domain/event/service/PopupStoreService.java
  src/main/java/com/example/onculture/global/exception/ErrorCode.java
  src/test/java/com/example/onculture/domain/event/service/ExhibitServiceTest.java
  src/test/java/com/example/onculture/domain/event/service/FestivalServiceTest.java
  src/test/java/com/example/onculture/domain/event/service/PopupStoreServiceTest.java
Labels: Fix

#150 Feat/profile/#149
  src/main/java/com/example/onculture/domain/user/controller/UserController.java
  src/main/java/com/example/onculture/domain/user/service/ImageFileService.java
  src/main/java/com/example/onculture/domain/user/service/UserService.java
Labels: Feat
